root -q -b 'examples/AfbUnfoldTests2D.cxx(0,"Pull","ttmass")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(1,"Pull","ttmass")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(2,"Pull","ttmass")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(3,"Pull","ttmass")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(4,"Pull","ttmass")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(5,"Pull","ttmass")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(6,"Pull","ttmass")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(7,"Pull","ttmass")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(0,"Linearity","ttmass")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(1,"Linearity","ttmass")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(2,"Linearity","ttmass")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(3,"Linearity","ttmass")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(4,"Linearity","ttmass")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(5,"Linearity","ttmass")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(6,"Linearity","ttmass")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(7,"Linearity","ttmass")' 
root -q -b 'examples/AfbUnfoldTests2D.cxx(0,"Pull","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(1,"Pull","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(2,"Pull","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(3,"Pull","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(4,"Pull","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(5,"Pull","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(6,"Pull","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(7,"Pull","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(0,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(1,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(2,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(3,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(4,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(5,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(6,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(7,"Linearity","ttpt")' 
root -q -b 'examples/AfbUnfoldTests2D.cxx(0,"Pull","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(1,"Pull","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(2,"Pull","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(3,"Pull","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(4,"Pull","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(5,"Pull","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(6,"Pull","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(7,"Pull","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(0,"Linearity","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(1,"Linearity","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(2,"Linearity","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(3,"Linearity","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(4,"Linearity","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(5,"Linearity","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(6,"Linearity","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(7,"Linearity","ttrapidity2")' 
