root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(0,"Linearity","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(1,"Linearity","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(2,"Linearity","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(4,"Linearity","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(0,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(1,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(2,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(4,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(0,"Linearity","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(1,"Linearity","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(2,"Linearity","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(4,"Linearity","ttrapidity2")' 
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(3,"Linearity","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(5,"Linearity","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(6,"Linearity","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(7,"Linearity","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(3,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(5,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(6,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(7,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(3,"Linearity","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(5,"Linearity","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(6,"Linearity","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D_weightMCtoData.cxx(7,"Linearity","ttrapidity2")' &
