root -q -b 'examples/AfbUnfoldTests2D.cxx(0,"Pull","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(1,"Pull","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(2,"Pull","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(3,"Pull","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(4,"Pull","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(5,"Pull","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(6,"Pull","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(7,"Pull","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(0,"Linearity","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(1,"Linearity","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(2,"Linearity","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(3,"Linearity","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(4,"Linearity","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(5,"Linearity","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(6,"Linearity","mtt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(7,"Linearity","mtt")' 
root -q -b 'examples/AfbUnfoldTests2D.cxx(0,"Pull","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(1,"Pull","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(2,"Pull","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(3,"Pull","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(4,"Pull","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(5,"Pull","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(6,"Pull","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(7,"Pull","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(0,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(1,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(2,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(3,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(4,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(5,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(6,"Linearity","ttpt")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(7,"Linearity","ttpt")' 
root -q -b 'examples/AfbUnfoldTests2D.cxx(0,"Pull","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(1,"Pull","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(2,"Pull","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(3,"Pull","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(4,"Pull","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(5,"Pull","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(6,"Pull","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(7,"Pull","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(0,"Linearity","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(1,"Linearity","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(2,"Linearity","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(3,"Linearity","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(4,"Linearity","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(5,"Linearity","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(6,"Linearity","ttrapidity2")' &
root -q -b 'examples/AfbUnfoldTests2D.cxx(7,"Linearity","ttrapidity2")' 
